version: "3.7"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - angiday-microservice-network

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
      - angiday-microservice-network
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: angiday_dev
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  angiday-discovery-service:
    container_name: angiday-discovery-service
    build: ./discovery-service
    restart: on-failure
    networks:
      - angiday-microservice-network

networks:
  angiday-microservice-network:
    driver: bridge
